version: "3.8"

services:
  fastapi:
    build: .
    volumes :
      - .:/app
      - /app/.venv
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres-db
      - redis-cache

  postgres-db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis-cache:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: